# Generated by Django 3.1.5 on 2021-01-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '选项管理', 'verbose_name_plural': '选项管理'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '问题管理', 'verbose_name_plural': '问题管理'},
        ),
    ]
