# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-12-18 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20201218_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': '权限管理', 'verbose_name_plural': '权限管理'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色管理', 'verbose_name_plural': '角色管理'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
    ]
